weights: ''
cfg: cfg/yolor_p6.cfg
data: flir.yaml
hyp: /dli/task/FLIR_YOLOR/data/hyp.scratch.1280.yaml
epochs: 10
batch_size: 6
img_size:
- 1280
- 1280
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: 0
log_imgs: 16
workers: 8
project: runs/train
name: yolor_p6
exist_ok: false
total_batch_size: 24
world_size: 4
global_rank: 0
save_dir: runs/train/yolor_p62
